export const CAPITALS_MAP = {
  "AF": "Cabul", "AL": "Tirana", "DZ": "Argel", "AD": "Andorra-a-Velha", "AO": "Luanda",
  "AR": "Buenos Aires", "AM": "Erevã", "AU": "Camberra", "AT": "Viena", "AZ": "Baku", 
  "BS": "Nassau", "BH": "Manama", "BD": "Daca", "BB": "Bridgetown", "BY": "Minsk",
  "BE": "Bruxelas", "BZ": "Belmopan", "BJ": "Porto Novo", "BT": "Timbu", "BO": "Sucre", 
  "BA": "Sarajevo", "BW": "Gaborone", "BR": "Brasília", "BN": "Bandar Seri Begawan", "BG": "Sófia", 
  "BF": "Ouagadougou", "BI": "Bujumbura", "KH": "Phnom Penh", "CM": "Yaoundé", "CA": "Ottawa", 
  "CV": "Praia", "CF": "Bangui", "TD": "N'Djamena", "CL": "Santiago", "CN": "Pequim", 
  "CO": "Bogotá", "KM": "Moroni", "CG": "Brazzaville", "CD": "Kinshasa", "CR": "San José", 
  "HR": "Zagrebe", "CU": "Havana", "CY": "Nicósia", "CZ": "Praga", "DK": "Copenhaga", 
  "DO": "Santo Domingo", "EC": "Quito", "EG": "Cairo", "SV": "San Salvador", "GQ": "Malabo", 
  "ER": "Asmara", "EE": "Tallinn", "ET": "Adis Abeba", "FI": "Helsínquia", "FJ": "Suva", 
  "FR": "Paris", "GA": "Libreville", "GM": "Banjul", "GE": "Tbilisi", "DE": "Berlim",
  "GH": "Acra", "GR": "Atenas", "GT": "Cidade da Guatemala", "GN": "Conacri", "GW": "Bissau", 
  "GY": "Georgetown", "HT": "Porto Príncipe", "HN": "Tegucigalpa", "HU": "Budapeste", "IS": "Reiquiavique", 
  "IN": "Nova Deli", "ID": "Jacarta", "IR": "Teerão", "IQ": "Bagdade", "IE": "Dublin",
  "IL": "Jerusalém", "IT": "Roma", "JM": "Kingston", "JP": "Tóquio", "JO": "Amã", 
  "KZ": "Astana", "KE": "Nairóbi", "KP": "Pyongyang", "KR": "Seul", "KW": "Kuwait", 
  "KG": "Bishkek", "LA": "Vientiane", "LV": "Riga", "LB": "Beirute", "LY": "Trípoli",
  "LT": "Vilnius", "LU": "Luxemburgo", "MG": "Antananarivo", "MW": "Lilongwe", "MY": "Kuala Lumpur",
  "MV": "Malé", "ML": "Bamako", "MT": "Valeta", "MA": "Rabat", "MZ": "Maputo", 
  "MM": "Naypyidaw", "NA": "Windhoek", "NP": "Katmandu", "NL": "Amesterdão", "NZ": "Wellington", 
  "NI": "Manágua", "NE": "Niamey", "NG": "Abuja", "NO": "Oslo", "OM": "Mascate",
  "PK": "Islamabade", "PA": "Cidade do Panamá", "PY": "Assunção", "PE": "Lima", "PH": "Manila", 
  "PL": "Varsóvia", "PT": "Lisboa", "QA": "Doha", "RO": "Bucareste", "RU": "Moscovo", 
  "RW": "Kigali", "SA": "Riade", "SN": "Dakar", "RS": "Belgrado", "SG": "Singapura", 
  "SK": "Bratislava", "SI": "Liubliana", "ZA": "Pretória", "ES": "Madrid", "LK": "Colombo", 
  "SD": "Cartum", "SE": "Estocolmo", "CH": "Berna", "SY": "Damasco", "TW": "Taipé", 
  "TZ": "Dodoma", "TH": "Banguecoque", "TN": "Tunes", "TR": "Ancara", "UG": "Kampala", 
  "UA": "Kiev", "AE": "Abu Dhabi", "GB": "Londres", "US": "Washington, D.C.", "UY": "Montevideu", 
  "UZ": "Tashkent", "VE": "Caracas", "VN": "Hanói", "YE": "Sana", "ZM": "Lusaka", "ZW": "Harare"
};
