export const CONTINENT_KEYS = ['Americas', 'Europe', 'Africa', 'Asia', 'Oceania'];

export const SEASON_CONFIG = {
  id: 'horizonte-2026-rotas',
  name: 'Rotas do Horizonte',
  subtitle: 'Temporada viva com foco em precisao, dominio continental e progresso persistente.',
  baseXpPerLevel: 420,
  xpCurvePerLevel: 55,
};

export const WEEKLY_MISSION_POOL = [
  {
    id: 'mission-runs-3',
    type: 'complete_runs',
    target: 3,
    title: 'Abrir novas rotas',
    description: 'Complete 3 partidas em qualquer modo.',
    rewardCoins: 180,
    rewardXp: 110,
    tone: 'sky',
  },
  {
    id: 'mission-correct-18',
    type: 'correct_answers',
    target: 18,
    title: 'Cartografo atento',
    description: 'Some 18 acertos na semana.',
    rewardCoins: 220,
    rewardXp: 140,
    tone: 'emerald',
  },
  {
    id: 'mission-study-2',
    type: 'study_sessions',
    target: 2,
    title: 'Sala de navegacao',
    description: 'Conclua 2 rodadas no modo estudo.',
    rewardCoins: 150,
    rewardXp: 120,
    tone: 'indigo',
  },
  {
    id: 'mission-daily-1',
    type: 'daily_wins',
    target: 1,
    title: 'Pulso diario',
    description: 'Venca o desafio diario uma vez.',
    rewardCoins: 260,
    rewardXp: 180,
    tone: 'amber',
  },
  {
    id: 'mission-football-1',
    type: 'football_wins',
    target: 1,
    title: 'Rota dos gramados',
    description: 'Conclua uma corrida de futebol.',
    rewardCoins: 240,
    rewardXp: 160,
    tone: 'rose',
  },
  {
    id: 'mission-perfect-1',
    type: 'perfect_runs',
    target: 1,
    title: 'Mapa limpo',
    description: 'Finalize uma sessao sem erros.',
    rewardCoins: 280,
    rewardXp: 200,
    tone: 'fuchsia',
  },
  {
    id: 'mission-combo-7',
    type: 'combo_chain',
    target: 7,
    title: 'Combustao alta',
    description: 'Alcance combo 7 em qualquer partida.',
    rewardCoins: 210,
    rewardXp: 170,
    tone: 'orange',
  },
  {
    id: 'mission-americas-8',
    type: 'continent_hits',
    continent: 'Americas',
    target: 8,
    title: 'Circuito das Americas',
    description: 'Acumule 8 acertos nas Americas.',
    rewardCoins: 160,
    rewardXp: 130,
    tone: 'teal',
  },
  {
    id: 'mission-europe-8',
    type: 'continent_hits',
    continent: 'Europe',
    target: 8,
    title: 'Rota europeia',
    description: 'Acumule 8 acertos na Europa.',
    rewardCoins: 160,
    rewardXp: 130,
    tone: 'sky',
  },
  {
    id: 'mission-africa-6',
    type: 'continent_hits',
    continent: 'Africa',
    target: 6,
    title: 'Travessia africana',
    description: 'Acumule 6 acertos na Africa.',
    rewardCoins: 160,
    rewardXp: 130,
    tone: 'amber',
  },
  {
    id: 'mission-asia-8',
    type: 'continent_hits',
    continent: 'Asia',
    target: 8,
    title: 'Passagem oriental',
    description: 'Acumule 8 acertos na Asia.',
    rewardCoins: 160,
    rewardXp: 130,
    tone: 'indigo',
  },
  {
    id: 'mission-oceania-4',
    type: 'continent_hits',
    continent: 'Oceania',
    target: 4,
    title: 'Linha oceanica',
    description: 'Acumule 4 acertos na Oceania.',
    rewardCoins: 160,
    rewardXp: 130,
    tone: 'cyan',
  },
];

export const ROTATING_EVENTS = [
  {
    id: 'event-coin-rush',
    title: 'Mare de Ouro',
    description: 'Partidas concluidas pagam 20% mais moedas.',
    rewardLabel: '+20% moedas por partida',
    coinMultiplier: 1.2,
    tone: 'amber',
  },
  {
    id: 'event-precision-burst',
    title: 'Janela de Precisao',
    description: 'Combos rapidos rendem XP extra de temporada.',
    rewardLabel: '+35 XP por combo rapido',
    comboXpBonus: 35,
    tone: 'cyan',
  },
  {
    id: 'event-study-drive',
    title: 'Expedicao Academica',
    description: 'Modo estudo rende 30% mais XP.',
    rewardLabel: '+30% XP no estudo',
    modeXpMultipliers: { study: 1.3 },
    tone: 'indigo',
  },
  {
    id: 'event-americas-focus',
    title: 'Radar das Americas',
    description: 'Acertos nas Americas geram bonus extra.',
    rewardLabel: '+4 moedas e +18 XP por acerto nas Americas',
    continentBonuses: {
      Americas: { coinsPerHit: 4, xpPerHit: 18 },
    },
    tone: 'emerald',
  },
  {
    id: 'event-world-tour',
    title: 'Tour Global',
    description: 'Vencer em qualquer modo gera um pacote extra de XP e moedas.',
    rewardLabel: 'Bonus de encerramento ao vencer',
    winBonusCoins: 90,
    winBonusXp: 120,
    tone: 'rose',
  },
];

export const CONTINENT_MILESTONES = {
  Americas: [6, 14, 24, 36],
  Europe: [6, 14, 24, 36],
  Africa: [5, 12, 20, 30],
  Asia: [6, 14, 24, 36],
  Oceania: [3, 7, 12, 18],
};

export const DEFAULT_ROUTE_UPGRADES = {
  atlasPass: 0,
  relayCore: 0,
  treasureRadar: 0,
};
